# Generated by Django 5.0.1 on 2024-01-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
